CREATE TABLE `book` (
`id` INT4 PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
`name` VARCHAR ( 300 ) DEFAULT NULL COMMENT '名称',
`address` text DEFAULT NULL COMMENT '描述',
`price` NUMERIC ( 20, 4 ) COMMENT '价格',
`number` INT4 COMMENT '数量'
) COMMENT '书籍' ENGINE = INNODB DEFAULT CHARSET = utf8;
